version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: med_postgres
    restart: always
    environment:
      POSTGRES_DB: med_warehouse
      POSTGRES_USER: med_user
      POSTGRES_PASSWORD: med_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: